# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [6]:
np.version.version

'1.19.2'

#### Q3 : Créer un vecteur nul de taille 10

In [11]:
vecteur = np.zeros(10); vecteur

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [10]:
vecteur2 = np.zeros(10)
vecteur2[3] = 1

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [17]:
Z = np.arange(10,50); Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [23]:
np.flip(Z)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [68]:
matrice = np.array([[1,2,3],[4,5,6],[7,8,2]]);matrice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 2]])

#### Q8 : Créer une matrice identié 3x3 

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [105]:
matrice2 = np.random.rand(3,3,3)*10 ;matrice2

array([[[2.4946147 , 9.47468052, 5.1441757 ],
        [0.20258156, 3.73138152, 1.03925749],
        [7.22525816, 5.31168999, 5.49116043]],

       [[1.48778348, 2.09985161, 3.83010491],
        [7.47472568, 0.78266884, 9.87116009],
        [6.24541337, 1.29009333, 9.9639236 ]],

       [[2.19959394, 6.13616893, 7.39859533],
        [2.78170672, 1.87103339, 2.17368642],
        [4.8940934 , 4.45634968, 3.29517598]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [106]:
matrice3 = np.random.rand(10,10)*10
print(np.amin(matrice3))
print(np.amax(matrice3))

0.0758010296637579
9.961110675696517


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)